version: '3.8'

services:
  scripts-hub:
    build: ./
    command: ./start.sh db ./scripts-hub
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8080"

  db:
    restart: always
    image: postgres:latest
    ports:
      - "5433:5432"
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres